export const DEFAULT_SUITE_TIMEOUT_MS = 120_000;

export const ACTIVE_TEST_SUITES = [
  { id: "calculations", file: "tests/calculations.test.ts", nodeArgs: ["--experimental-strip-types"], groups: ["all"] },
  { id: "engagement", file: "tests/engagement.test.ts", nodeArgs: ["--experimental-strip-types"], groups: ["all"] },
  { id: "tax-integration", file: "tests/financial-freedom-tax-integration.test.mjs", groups: ["all", "mjs"] },
  { id: "financial-progress-history", file: "tests/financial-progress-history.test.mjs", groups: ["all", "mjs"] },
  { id: "calculation-audit-2026-27", file: "tests/calculation-audit-2026-27.test.mjs", groups: ["all", "mjs", "audit"] },
  { id: "main-calculator-zero-balance-loan-r3-blocker", file: "tests/main-calculator-zero-balance-loan-r3-blocker.test.mjs", groups: ["all", "mjs", "audit", "r3-blocker"] },
  { id: "semi-retirement-projection", file: "tests/semi-retirement-projection.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "semi-retirement-ui", file: "tests/semi-retirement-ui.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "semi-retirement-integration-v1", file: "tests/semi-retirement-integration-v1.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "stage-a", file: "tests/semi-retirement-debt-property-stage-a.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "stage-a1", file: "tests/semi-retirement-debt-property-stage-a1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-a1"] },
  { id: "stage-b", file: "tests/semi-retirement-debt-property-stage-b.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b"] },
  { id: "stage-b1", file: "tests/semi-retirement-debt-property-stage-b1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b1"] },
  { id: "stage-b1a", file: "tests/semi-retirement-debt-property-stage-b1a.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b1a"] },
  { id: "stage-c", file: "tests/semi-retirement-debt-property-stage-c.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-c"] },
  { id: "stage-c1", file: "tests/semi-retirement-debt-property-stage-c1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-c1"] },
  { id: "stage-d", file: "tests/semi-retirement-debt-property-stage-d.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-d"] },
  { id: "stage-e", file: "tests/semi-retirement-debt-property-stage-e.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-e"] },
  { id: "stage-e1", file: "tests/semi-retirement-debt-property-stage-e1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-e1"] },
  { id: "stage-g2ea", file: "tests/semi-retirement-surplus-routing-g2ea.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2ea"] },
  { id: "stage-g2es", file: "tests/semi-retirement-concessional-events-g2es.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2es"] },
  { id: "stage-g2es1", file: "tests/semi-retirement-concessional-tax-treatment-g2es1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2es1"] },
  { id: "stage-g2g", file: "tests/semi-retirement-follow-up-g2g.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2g"] },
  { id: "stage-g2h", file: "tests/sample-plans-multi-comparison-g2h.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2h"] },
  { id: "ai-containment-r1", file: "tests/ai-containment-r1.test.mjs", groups: ["all", "mjs", "r1-ai"] },
];

export const SYNTAX_CHECK_FILES = [
  "app.js",
  "api/ai-insights.js",
  "calculator.js",
  "semiRetirementProjection.js",
  "semiRetirementUi.js",
  "weekly-plan.js",
  "weekly-planner-export.js",
  "scripts/run-tests.mjs",
  "scripts/verify-test-inventory.mjs",
  "scripts/run-syntax-checks.mjs",
  "scripts/run-test-suite-worker.mjs",
  "scripts/runner-self-test.mjs",
  "scripts/scan-secrets.mjs",
  "scripts/scan-secrets-self-test.mjs",
  "scripts/test-inventory.mjs",
  "scripts/r1-numerical-parity.mjs",
  "scripts/r1-numerical-parity-self-test.mjs",
  "tests/main-calculator-zero-balance-loan-r3-blocker.test.mjs",
];
