window.FFS_DATA = {
  disclaimer: "This tool is for education and modelling only and is not financial advice.",
  demoPlan: {
    personal: {
      person1Name: "James",
      person2Name: "Sarah",
      person1Age: 42,
      person2Age: 41,
      workOptionalAge: 50,
      semiRetirementAge: 55,
      fullRetirementAge: 60,
      targetAnnualSpending: 90000,
    },
    assets: {
      homeValue: 900000,
      otherPropertyValue: 0,
      offsetBalance: 90000,
      cash: 0,
      sharesEtfs: 70000,
      crypto: 10000,
      superPerson1: 130000,
      superPerson2: 110000,
      vehiclesPersonalAssets: 30000,
    },
    liabilities: {
      homeLoanBalance: 550000,
      homeLoanInterestRatePct: 6.1,
      monthlyRepayment: 3400,
      remainingLoanTermYears: 30,
      hecsHelpDebt: 0,
      otherDebts: 0,
    },
    income: {
      person1IncomeName: "James net income",
      person1Income: 2400,
      person1Frequency: "fortnightly",
      person2IncomeName: "Sarah net income",
      person2Income: 2300,
      person2Frequency: "fortnightly",
      otherIncomeName: "Other Income",
      otherIncome: 5000,
      otherIncomeFrequency: "annually",
    },
    incomeItems: [
      { id: "income-james", name: "James net income", amount: 2400, frequency: "fortnightly" },
      { id: "income-sarah", name: "Sarah net income", amount: 2300, frequency: "fortnightly" },
      { id: "income-other", name: "Other Income", amount: 5000, frequency: "annually" },
    ],
    expenses: {
      livingName: "Living costs",
      livingCosts: 4000,
      livingFrequency: "monthly",
      mortgageRepayments: 3400,
      foodName: "Food",
      food: 300,
      foodFrequency: "weekly",
      utilitiesName: "Utilities",
      utilities: 4000,
      utilitiesFrequency: "annually",
      insuranceName: "Insurance",
      insurance: 2500,
      insuranceFrequency: "annually",
      schoolChildrenName: "School / kids",
      schoolChildren: 3000,
      schoolChildrenFrequency: "annually",
      ratesPropertyCostsName: "Rates / property costs",
      ratesPropertyCosts: 4000,
      ratesPropertyCostsFrequency: "annually",
      otherExpensesName: "Other expenses",
      otherExpenses: 0,
      otherFrequency: "monthly",
    },
    expenseItems: [
      { id: "expense-living", name: "Living costs", category: "living", amount: 4000, frequency: "monthly" },
      { id: "expense-food", name: "Food", category: "food", amount: 300, frequency: "weekly" },
      { id: "expense-utilities", name: "Utilities", category: "utilities", amount: 4000, frequency: "annually" },
      { id: "expense-insurance", name: "Insurance", category: "insurance", amount: 2500, frequency: "annually" },
      { id: "expense-school", name: "School / kids", category: "schoolChildren", amount: 3000, frequency: "annually" },
      { id: "expense-rates", name: "Rates / property costs", category: "ratesPropertyCosts", amount: 4000, frequency: "annually" },
    ],
    assetItems: [
      { id: "asset-home", name: "Home", category: "home", value: 900000 },
      { id: "asset-offset", name: "Offset account", category: "offset", value: 90000 },
      { id: "asset-shares", name: "Shares / ETFs", category: "shares", value: 70000 },
      { id: "asset-crypto", name: "Crypto", category: "crypto", value: 10000 },
      { id: "asset-super-1", name: "Super person 1", category: "super", value: 130000 },
      { id: "asset-super-2", name: "Super person 2", category: "super", value: 110000 },
      { id: "asset-vehicles", name: "Vehicles / personal assets", category: "vehicle", value: 30000 },
    ],
    investing: {
      annualInvestingTarget: 30000,
      employerSuperContributions: 22000,
      extraSuperContributions: 0,
      expectedInvestmentReturnPct: 8,
      expectedSuperReturnPct: 8,
      inflationPct: 2.5,
      safeWithdrawalRatePct: 4,
    },
    liabilityItems: [
      { id: "liability-home-loan", name: "Home loan", type: "homeLoan", balance: 550000, interestRatePct: 6.1, repayment: 3400, repaymentFrequency: "monthly", termYears: 30 },
    ],
    comparison: {
      increaseIncome: 0,
      reduceIncome: 0,
      increaseExpenses: 0,
      reduceExpenses: 0,
    },
    downsizing: {
      enabled: false,
      currentResidenceValue: 900000,
      futurePropertyValue: 550000,
      sellingCosts: 25000,
      buyingCosts: 35000,
      releasedForInvestment: 290000,
    },
  },
};
