window.FFS_DATA = {
  disclaimer: "This tool is for education and modelling only and is not financial advice.",
  demoPlan: {
    personal: {
      person1Name: "James",
      person2Name: "Sarah",
      person1Age: 42,
      person2Age: 41,
      workOptionalAge: 50,
      semiRetirementAge: 55,
      fullRetirementAge: 60,
      targetAnnualSpending: 90000,
    },
    assets: {
      homeValue: 900000,
      otherPropertyValue: 0,
      offsetBalance: 90000,
      cash: 0,
      sharesEtfs: 70000,
      crypto: 10000,
      superPerson1: 130000,
      superPerson2: 110000,
      vehiclesPersonalAssets: 30000,
    },
    liabilities: {
      homeLoanBalance: 550000,
      homeLoanInterestRatePct: 6.1,
      monthlyRepayment: 3400,
      remainingLoanTermYears: 30,
      hecsHelpDebt: 0,
      otherDebts: 0,
    },
    income: {
      person1IncomeName: "James net income",
      person1Income: 2400,
      person1Frequency: "fortnightly",
      person2IncomeName: "Sarah net income",
      person2Income: 2300,
      person2Frequency: "fortnightly",
      otherIncomeName: "Other Income",
      otherIncome: 5000,
      otherIncomeFrequency: "annually",
    },
    expenses: {
      livingName: "Living costs",
      livingCosts: 4000,
      livingFrequency: "monthly",
      mortgageRepayments: 3400,
      foodName: "Food",
      food: 300,
      foodFrequency: "weekly",
      utilitiesName: "Utilities",
      utilities: 4000,
      utilitiesFrequency: "annually",
      insuranceName: "Insurance",
      insurance: 2500,
      insuranceFrequency: "annually",
      schoolChildrenName: "School / kids",
      schoolChildren: 3000,
      schoolChildrenFrequency: "annually",
      ratesPropertyCostsName: "Rates / property costs",
      ratesPropertyCosts: 4000,
      ratesPropertyCostsFrequency: "annually",
      otherExpensesName: "Other expenses",
      otherExpenses: 0,
      otherFrequency: "monthly",
    },
    investing: {
      annualInvestingTarget: 30000,
      employerSuperContributions: 22000,
      extraSuperContributions: 0,
      expectedInvestmentReturnPct: 8,
      expectedSuperReturnPct: 8,
      inflationPct: 2.5,
      safeWithdrawalRatePct: 4,
    },
    downsizing: {
      enabled: false,
      currentResidenceValue: 900000,
      futurePropertyValue: 550000,
      sellingCosts: 25000,
      buyingCosts: 35000,
      releasedForInvestment: 290000,
    },
  },
};
