function sampleIncome(id, name, amount, frequency = "annually", extra = {}) {
  return {
    id,
    name,
    amount,
    frequency,
    annualAmount: amount,
    ...extra,
  };
}

function sampleExpense(id, name, category, amount, frequency = "annually") {
  return { id, name, category, amount, frequency };
}

function sampleAsset(id, name, category, value, extra = {}) {
  return { id, name, category, value, ...extra };
}

function sampleLiability(id, name, type, balance, repayment, extra = {}) {
  return {
    id,
    name,
    type,
    balance,
    repayment,
    repaymentFrequency: extra.repaymentFrequency || "monthly",
    interestRatePct: extra.interestRatePct ?? 0,
    termYears: extra.termYears ?? 0,
    ...extra,
  };
}

function makeSamplePlan(config) {
  const person2Name = config.person2Name || "";
  const hasPerson2 = Boolean(person2Name);
  const personal = {
    person1Name: config.person1Name,
    person2Name,
    person1Age: config.person1Age,
    person2Age: hasPerson2 ? config.person2Age : 0,
    dependants: config.dependants || 0,
    workOptionalAge: config.workOptionalAge,
    semiRetirementAge: config.semiRetirementAge,
    fullRetirementAge: config.fullRetirementAge,
    targetAnnualSpending: config.targetAnnualSpending,
  };
  const income = {
    person1IncomeName: `${config.person1Name} salary`,
    person1Income: config.person1Income || 0,
    person1Frequency: config.person1Frequency || "annually",
    person2IncomeName: hasPerson2 ? `${person2Name} salary` : "",
    person2Income: hasPerson2 ? (config.person2Income || 0) : 0,
    person2Frequency: config.person2Frequency || "annually",
    otherIncomeName: config.otherIncomeName || "Other Income",
    otherIncome: config.otherIncome || 0,
    otherIncomeFrequency: config.otherIncomeFrequency || "annually",
    person1HasStslDebt: Boolean(config.person1StslBalance),
    person2HasStslDebt: Boolean(config.person2StslBalance),
    person1HospitalCoverStatus: config.person1HospitalCoverStatus || "full-year",
    person2HospitalCoverStatus: hasPerson2 ? (config.person2HospitalCoverStatus || "full-year") : "",
    person1HospitalCoverDays: config.person1HospitalCoverDays ?? 365,
    person2HospitalCoverDays: hasPerson2 ? (config.person2HospitalCoverDays ?? 365) : 0,
  };
  const incomeItems = [
    sampleIncome("income-person1-salary", `${config.person1Name} salary`, config.person1Income || 0, config.person1Frequency || "annually", {
      category: "salary_wages",
      type: "salary_wages",
      owner: "person1",
    }),
  ];
  if (hasPerson2) {
    incomeItems.push(sampleIncome("income-person2-salary", `${person2Name} salary`, config.person2Income || 0, config.person2Frequency || "annually", {
      category: "salary_wages",
      type: "salary_wages",
      owner: "person2",
    }));
  }
  (config.extraIncomeItems || []).forEach((item, index) => {
    incomeItems.push(sampleIncome(
      item.id || `income-extra-${index + 1}`,
      item.name,
      item.amount || 0,
      item.frequency || "annually",
      {
        category: item.category || item.type || "other",
        type: item.type || item.category || "other",
        owner: item.owner || "joint",
        passiveIncome: Boolean(item.passiveIncome),
        person1AllocationPercentage: item.person1AllocationPercentage,
        person2AllocationPercentage: item.person2AllocationPercentage,
      },
    ));
  });
  const assets = {
    homeValue: config.homeValue || 0,
    otherPropertyValue: config.otherPropertyValue || 0,
    offsetBalance: config.offsetBalance || 0,
    cash: config.cash || 0,
    sharesEtfs: config.sharesEtfs || 0,
    crypto: config.crypto || 0,
    superPerson1: config.superPerson1 || 0,
    superPerson2: hasPerson2 ? (config.superPerson2 || 0) : 0,
    vehiclesPersonalAssets: config.vehiclesPersonalAssets || 0,
  };
  const assetItems = [
    sampleAsset("asset-home", "Home", "home", assets.homeValue),
    sampleAsset("asset-offset", "Offset account", "offset", assets.offsetBalance),
    sampleAsset("asset-cash", "Cash savings", "cash", assets.cash),
    sampleAsset("asset-shares", "Investment portfolio", "shares", assets.sharesEtfs),
    sampleAsset("asset-crypto", "Cryptocurrency", "crypto", assets.crypto),
    sampleAsset("asset-super-person1", `${config.person1Name} super`, "super", assets.superPerson1, { owner: "person1" }),
    sampleAsset("asset-vehicles", "Vehicles and personal assets", "vehicle", assets.vehiclesPersonalAssets),
  ].filter((asset) => Number(asset.value) > 0 || ["asset-home", "asset-offset", "asset-cash", "asset-shares", "asset-super-person1"].includes(asset.id));
  if (hasPerson2) {
    assetItems.splice(assetItems.findIndex((asset) => asset.id === "asset-vehicles"), 0, sampleAsset("asset-super-person2", `${person2Name} super`, "super", assets.superPerson2, { owner: "person2" }));
  }
  if (assets.otherPropertyValue > 0) {
    assetItems.splice(assetItems.findIndex((asset) => asset.id === "asset-super-person1"), 0, sampleAsset("asset-rental-property", "Rental property", "investmentProperty", assets.otherPropertyValue, { owner: "joint" }));
  }
  const liabilities = {
    homeLoanBalance: config.homeLoanBalance || 0,
    homeLoanInterestRatePct: config.homeLoanInterestRatePct || 0,
    monthlyRepayment: config.monthlyRepayment || 0,
    remainingLoanTermYears: config.remainingLoanTermYears || 0,
    hecsHelpDebt: (config.person1StslBalance || 0) + (config.person2StslBalance || 0),
    otherDebts: config.otherDebts || 0,
    creditCardBalance: config.creditCardBalance || 0,
    creditCardInterestRatePct: config.creditCardInterestRatePct || 19.99,
    creditCardMonthlyRepayment: config.creditCardMonthlyRepayment || 0,
    creditCardLimit: config.creditCardLimit || 10000,
  };
  const liabilityItems = [
    sampleLiability("liability-home-loan", "Home loan", "homeLoan", liabilities.homeLoanBalance, liabilities.monthlyRepayment, {
      interestRatePct: liabilities.homeLoanInterestRatePct,
      repaymentFrequency: "monthly",
      termYears: liabilities.remainingLoanTermYears,
    }),
    sampleLiability("liability-stsl-person1", `${config.person1Name} - STSL`, "hecsHelp", config.person1StslBalance || 0, 0, {
      owner: "person1",
      subtype: "STSL",
    }),
  ];
  if (hasPerson2) {
    liabilityItems.push(sampleLiability("liability-stsl-person2", `${person2Name} - STSL`, "hecsHelp", config.person2StslBalance || 0, 0, {
      owner: "person2",
      subtype: "STSL",
    }));
  }
  if (config.investmentLoanBalance) {
    liabilityItems.push(sampleLiability("liability-rental-loan", "Rental property loan", "investmentLoan", config.investmentLoanBalance, config.investmentLoanRepayment || 0, {
      interestRatePct: config.investmentLoanInterestRatePct || 6.2,
      repaymentFrequency: "monthly",
      termYears: config.investmentLoanTermYears || 20,
      investmentLink: { assetCategory: "rental_property", linkedAssetId: "asset-rental-property" },
      linkedAssetId: "asset-rental-property",
      linkedRentalPropertyId: "asset-rental-property",
      principalRepayment: config.investmentLoanPrincipalRepayment || 0,
      interestOnlyRepayment: config.investmentLoanInterestRepayment || 0,
    }));
  }
  if (liabilities.creditCardBalance > 0) {
    liabilityItems.push(sampleLiability("liability-credit-card", "Credit card", "creditCard", liabilities.creditCardBalance, liabilities.creditCardMonthlyRepayment, {
      interestRatePct: liabilities.creditCardInterestRatePct,
      repaymentFrequency: "monthly",
      creditLimit: liabilities.creditCardLimit,
    }));
  }
  if (liabilities.otherDebts > 0) {
    liabilityItems.push(sampleLiability("liability-other-debt", "Other personal loan", "personalLoan", liabilities.otherDebts, config.otherDebtRepayment || 0, {
      interestRatePct: config.otherDebtInterestRatePct || 8.5,
      repaymentFrequency: "monthly",
      termYears: config.otherDebtTermYears || 5,
    }));
  }
  const expenses = {
    livingName: "Living costs",
    livingCosts: config.livingCosts || 0,
    livingFrequency: config.livingFrequency || "monthly",
    mortgageRepayments: liabilities.monthlyRepayment,
    foodName: "Food",
    food: config.food || 0,
    foodFrequency: config.foodFrequency || "weekly",
    utilitiesName: "Utilities",
    utilities: config.utilities || 0,
    utilitiesFrequency: config.utilitiesFrequency || "annually",
    insuranceName: "Insurance",
    insurance: config.insurance || 0,
    insuranceFrequency: config.insuranceFrequency || "annually",
    schoolChildrenName: "School / children",
    schoolChildren: config.schoolChildren || 0,
    schoolChildrenFrequency: config.schoolChildrenFrequency || "annually",
    ratesPropertyCostsName: "Rates / property costs",
    ratesPropertyCosts: config.ratesPropertyCosts || 0,
    ratesPropertyCostsFrequency: config.ratesPropertyCostsFrequency || "annually",
    otherExpensesName: "Other expenses",
    otherExpenses: config.otherExpenses || 0,
    otherFrequency: config.otherFrequency || "annually",
  };
  const expenseItems = [
    sampleExpense("expense-living", "Living costs", "living", expenses.livingCosts, expenses.livingFrequency),
    sampleExpense("expense-food", "Groceries and food", "food", expenses.food, expenses.foodFrequency),
    sampleExpense("expense-utilities", "Utilities", "utilities", expenses.utilities, expenses.utilitiesFrequency),
    sampleExpense("expense-insurance", "General insurance", "insurance", expenses.insurance, expenses.insuranceFrequency),
    sampleExpense("expense-school", "School and childcare", "schoolChildren", expenses.schoolChildren, expenses.schoolChildrenFrequency),
    sampleExpense("expense-rates", "Rates and property costs", "ratesPropertyCosts", expenses.ratesPropertyCosts, expenses.ratesPropertyCostsFrequency),
    sampleExpense("expense-subscriptions", "Subscriptions", "subscriptions", config.subscriptions || 0, "monthly"),
    sampleExpense("expense-phone", "Phone and internet", "phoneInternet", config.phoneInternet || 0, "monthly"),
    sampleExpense("expense-health", "Private health cover", "privateHealth", config.privateHealth || 0, "monthly"),
    sampleExpense("expense-transport", "Fuel and transport", "petrol", config.transport || 0, "weekly"),
    sampleExpense("expense-vehicle", "Vehicle registration and insurance", "vehicleCosts", config.vehicleCosts || 0, "annually"),
  ].filter((expense) => Number(expense.amount) > 0);
  const plan = {
    meta: {
      source: "sample",
      isDemo: true,
      samplePlanName: config.name,
    },
    personal,
    assets,
    liabilities,
    income,
    incomeItems,
    expenses,
    expenseItems,
    assetItems,
    liabilityItems,
    investing: {
      annualInvestingTarget: config.annualInvestingTarget || 0,
      employerSuperContributions: config.employerSuperContributions || Math.round(((config.person1Income || 0) + (config.person2Income || 0)) * 0.12),
      person1EmployerSuperOverrideEnabled: false,
      person2EmployerSuperOverrideEnabled: false,
      extraSuperContributions: config.extraSuperContributions || 0,
      expectedInvestmentReturnPct: config.expectedInvestmentReturnPct ?? 7,
      expectedSuperReturnPct: config.expectedSuperReturnPct ?? 6.5,
      inflationPct: config.inflationPct ?? 2.5,
      wageGrowthPct: config.wageGrowthPct ?? 3,
      safeWithdrawalRatePct: config.safeWithdrawalRatePct ?? 4,
      investmentPropertyCapitalGrowthRatePct: config.investmentPropertyCapitalGrowthRatePct ?? 3.5,
      principalResidenceCapitalGrowthRatePct: config.principalResidenceCapitalGrowthRatePct ?? 3.5,
    },
    goalItems: [
      { id: "goal-emergency", name: "Target emergency fund", current: assets.cash + assets.offsetBalance, target: config.emergencyFundTarget || Math.max(15000, Math.round((config.livingCosts || 0) * 6)) },
      { id: "goal-investments", name: "Investment portfolio target", current: assets.sharesEtfs + assets.crypto, target: config.investmentTarget || Math.max(assets.sharesEtfs + assets.crypto, 250000) },
      { id: "goal-super", name: "Super balance target", current: assets.superPerson1 + assets.superPerson2, target: config.superTarget || Math.max(assets.superPerson1 + assets.superPerson2, 650000) },
      { id: "goal-debt", name: "Debt reduction target", current: liabilities.homeLoanBalance + liabilities.creditCardBalance + liabilities.otherDebts + (config.investmentLoanBalance || 0), target: config.debtTarget ?? 0 },
      { id: "goal-net-worth", name: "Financial freedom net worth target", current: assets.homeValue + assets.otherPropertyValue + assets.cash + assets.offsetBalance + assets.sharesEtfs + assets.crypto + assets.superPerson1 + assets.superPerson2 + assets.vehiclesPersonalAssets - liabilities.homeLoanBalance - liabilities.creditCardBalance - liabilities.otherDebts - (config.investmentLoanBalance || 0), target: config.netWorthTarget || 1200000 },
    ],
    comparison: {},
    downsizing: config.downsizing || { enabled: false, currentResidenceValue: assets.homeValue, futurePropertyValue: 0, sellingCosts: 0, buyingCosts: 0, releasedForInvestment: 0 },
  };
  return {
    id: config.id,
    name: config.name,
    description: config.description,
    plan,
  };
}

const samplePlans = [
  makeSamplePlan({
    id: "young-professional",
    name: "Young Professional",
    description: "Single, early wealth building with STSL and regular investing.",
    person1Name: "Alex",
    person1Age: 29,
    dependants: 0,
    workOptionalAge: 45,
    semiRetirementAge: 55,
    fullRetirementAge: 60,
    targetAnnualSpending: 62000,
    person1Income: 98000,
    person1StslBalance: 36000,
    cash: 18000,
    sharesEtfs: 38000,
    crypto: 2500,
    superPerson1: 68000,
    vehiclesPersonalAssets: 12000,
    livingCosts: 2300,
    food: 145,
    utilities: 240,
    utilitiesFrequency: "monthly",
    insurance: 1250,
    otherExpenses: 7200,
    subscriptions: 75,
    phoneInternet: 95,
    privateHealth: 145,
    transport: 65,
    vehicleCosts: 1080,
    annualInvestingTarget: 12500,
    extraSuperContributions: 2000,
    emergencyFundTarget: 25000,
    investmentTarget: 320000,
    superTarget: 720000,
    netWorthTarget: 1250000,
  }),
  makeSamplePlan({
    id: "young-couple",
    name: "Young Couple",
    description: "Two incomes, first home loan and a positive early surplus.",
    person1Name: "Alex",
    person2Name: "Jordan",
    person1Age: 32,
    person2Age: 31,
    dependants: 0,
    workOptionalAge: 48,
    semiRetirementAge: 56,
    fullRetirementAge: 62,
    targetAnnualSpending: 78000,
    person1Income: 112000,
    person2Income: 86000,
    homeValue: 780000,
    offsetBalance: 32000,
    cash: 24000,
    sharesEtfs: 62000,
    crypto: 6000,
    superPerson1: 105000,
    superPerson2: 76000,
    vehiclesPersonalAssets: 35000,
    homeLoanBalance: 560000,
    homeLoanInterestRatePct: 6,
    monthlyRepayment: 3500,
    remainingLoanTermYears: 28,
    livingCosts: 3300,
    food: 240,
    utilities: 3900,
    insurance: 2300,
    ratesPropertyCosts: 3600,
    otherExpenses: 10400,
    subscriptions: 95,
    phoneInternet: 155,
    privateHealth: 250,
    transport: 105,
    vehicleCosts: 2150,
    annualInvestingTarget: 18000,
    extraSuperContributions: 2000,
    emergencyFundTarget: 40000,
    investmentTarget: 550000,
    superTarget: 1100000,
    debtTarget: 300000,
    netWorthTarget: 1800000,
    extraIncomeItems: [
      { id: "income-interest", name: "Joint interest", amount: 1800, category: "interest", owner: "joint", passiveIncome: true },
    ],
  }),
  makeSamplePlan({
    id: "growing-family",
    name: "Growing Family",
    description: "Mortgage, children, regular investing and a tighter weekly surplus.",
    person1Name: "Chris",
    person2Name: "Taylor",
    person1Age: 39,
    person2Age: 37,
    dependants: 2,
    workOptionalAge: 50,
    semiRetirementAge: 57,
    fullRetirementAge: 63,
    targetAnnualSpending: 88000,
    person1Income: 128000,
    person2Income: 78000,
    homeValue: 930000,
    offsetBalance: 42000,
    cash: 25000,
    sharesEtfs: 118000,
    crypto: 5000,
    superPerson1: 205000,
    superPerson2: 118000,
    vehiclesPersonalAssets: 48000,
    homeLoanBalance: 610000,
    homeLoanInterestRatePct: 6.05,
    monthlyRepayment: 4100,
    remainingLoanTermYears: 24,
    creditCardBalance: 2500,
    creditCardMonthlyRepayment: 250,
    livingCosts: 3900,
    food: 335,
    utilities: 4700,
    insurance: 2900,
    schoolChildren: 7200,
    ratesPropertyCosts: 4500,
    otherExpenses: 16200,
    subscriptions: 120,
    phoneInternet: 180,
    privateHealth: 310,
    transport: 145,
    vehicleCosts: 2800,
    annualInvestingTarget: 14500,
    extraSuperContributions: 2500,
    emergencyFundTarget: 52000,
    investmentTarget: 720000,
    superTarget: 1350000,
    debtTarget: 350000,
    netWorthTarget: 2300000,
    extraIncomeItems: [
      { id: "income-dividends", name: "Dividend income", amount: 4200, category: "dividends", owner: "joint", passiveIncome: true },
    ],
  }),
  makeSamplePlan({
    id: "established-family-wealth-building",
    name: "Established Family / Wealth Building",
    description: "Offset, investment property, passive income and meaningful investing.",
    person1Name: "Sam",
    person2Name: "Morgan",
    person1Age: 45,
    person2Age: 43,
    dependants: 2,
    workOptionalAge: 52,
    semiRetirementAge: 56,
    fullRetirementAge: 61,
    targetAnnualSpending: 94000,
    person1Income: 155000,
    person2Income: 105000,
    homeValue: 1180000,
    otherPropertyValue: 690000,
    offsetBalance: 115000,
    cash: 48000,
    sharesEtfs: 310000,
    crypto: 18000,
    superPerson1: 330000,
    superPerson2: 245000,
    vehiclesPersonalAssets: 62000,
    homeLoanBalance: 520000,
    homeLoanInterestRatePct: 5.95,
    monthlyRepayment: 4300,
    remainingLoanTermYears: 18,
    investmentLoanBalance: 410000,
    investmentLoanRepayment: 2850,
    investmentLoanPrincipalRepayment: 900,
    investmentLoanInterestRepayment: 1950,
    investmentLoanTermYears: 20,
    livingCosts: 4400,
    food: 360,
    utilities: 5200,
    insurance: 3900,
    schoolChildren: 9600,
    ratesPropertyCosts: 7600,
    otherExpenses: 17800,
    subscriptions: 140,
    phoneInternet: 195,
    privateHealth: 360,
    transport: 160,
    vehicleCosts: 3300,
    annualInvestingTarget: 36000,
    extraSuperContributions: 8000,
    emergencyFundTarget: 70000,
    investmentTarget: 1100000,
    superTarget: 1700000,
    debtTarget: 300000,
    netWorthTarget: 3200000,
    extraIncomeItems: [
      { id: "income-rental-net", name: "Rental property net cash income", amount: 14200, category: "rentalNetCashIncome", type: "rentalNetCashIncome", owner: "joint", passiveIncome: true },
      { id: "income-distributions", name: "Managed fund distributions", amount: 7600, category: "distributions", type: "distributions", owner: "joint", passiveIncome: true },
    ],
  }),
  makeSamplePlan({
    id: "pre-retirement",
    name: "Pre-Retirement",
    description: "Approaching retirement with high super and reduced debt.",
    person1Name: "David",
    person2Name: "Michelle",
    person1Age: 57,
    person2Age: 55,
    dependants: 0,
    workOptionalAge: 58,
    semiRetirementAge: 60,
    fullRetirementAge: 63,
    targetAnnualSpending: 98000,
    person1Income: 118000,
    person2Income: 82000,
    homeValue: 1250000,
    otherPropertyValue: 760000,
    offsetBalance: 135000,
    cash: 85000,
    sharesEtfs: 720000,
    crypto: 0,
    superPerson1: 620000,
    superPerson2: 520000,
    vehiclesPersonalAssets: 52000,
    homeLoanBalance: 180000,
    homeLoanInterestRatePct: 5.85,
    monthlyRepayment: 2600,
    remainingLoanTermYears: 7,
    investmentLoanBalance: 260000,
    investmentLoanRepayment: 2200,
    investmentLoanPrincipalRepayment: 750,
    investmentLoanInterestRepayment: 1450,
    investmentLoanTermYears: 12,
    livingCosts: 4850,
    food: 285,
    utilities: 5200,
    insurance: 3800,
    ratesPropertyCosts: 7200,
    otherExpenses: 13000,
    subscriptions: 120,
    phoneInternet: 165,
    privateHealth: 330,
    transport: 105,
    vehicleCosts: 3000,
    annualInvestingTarget: 22000,
    extraSuperContributions: 12000,
    emergencyFundTarget: 85000,
    investmentTarget: 950000,
    superTarget: 1650000,
    debtTarget: 0,
    netWorthTarget: 3600000,
    extraIncomeItems: [
      { id: "income-rental-pre", name: "Rental property net cash income", amount: 11800, category: "rentalNetCashIncome", type: "rentalNetCashIncome", owner: "joint", passiveIncome: true },
      { id: "income-interest-pre", name: "Interest income", amount: 5200, category: "interest", owner: "joint", passiveIncome: true },
    ],
  }),
  makeSamplePlan({
    id: "semi-retirement",
    name: "Semi-Retirement",
    description: "Reduced work before full retirement, with investments bridging to super.",
    person1Name: "Jamie",
    person2Name: "Casey",
    person1Age: 50,
    person2Age: 49,
    dependants: 1,
    workOptionalAge: 50,
    semiRetirementAge: 52,
    fullRetirementAge: 62,
    targetAnnualSpending: 90000,
    person1Income: 135000,
    person2Income: 96000,
    homeValue: 1080000,
    offsetBalance: 90000,
    cash: 60000,
    sharesEtfs: 520000,
    crypto: 12000,
    superPerson1: 430000,
    superPerson2: 360000,
    vehiclesPersonalAssets: 48000,
    homeLoanBalance: 310000,
    homeLoanInterestRatePct: 5.9,
    monthlyRepayment: 3200,
    remainingLoanTermYears: 13,
    livingCosts: 4300,
    food: 310,
    utilities: 4700,
    insurance: 3400,
    schoolChildren: 3600,
    ratesPropertyCosts: 5600,
    otherExpenses: 15000,
    subscriptions: 110,
    phoneInternet: 170,
    privateHealth: 320,
    transport: 125,
    vehicleCosts: 2900,
    annualInvestingTarget: 30000,
    extraSuperContributions: 10000,
    emergencyFundTarget: 75000,
    investmentTarget: 900000,
    superTarget: 1500000,
    debtTarget: 120000,
    netWorthTarget: 3000000,
    extraIncomeItems: [
      { id: "income-dividends-semi", name: "Dividends and distributions", amount: 15500, category: "dividends", owner: "joint", passiveIncome: true },
    ],
  }),
  makeSamplePlan({
    id: "retirement-ready",
    name: "Retirement Ready",
    description: "Little debt, high super and a completed retirement spending target.",
    person1Name: "Peter",
    person2Name: "Susan",
    person1Age: 60,
    person2Age: 60,
    dependants: 0,
    workOptionalAge: 60,
    semiRetirementAge: 62,
    fullRetirementAge: 65,
    targetAnnualSpending: 92000,
    person1Income: 55000,
    person2Income: 32000,
    homeValue: 1150000,
    offsetBalance: 40000,
    cash: 95000,
    sharesEtfs: 420000,
    crypto: 0,
    superPerson1: 920000,
    superPerson2: 780000,
    vehiclesPersonalAssets: 45000,
    homeLoanBalance: 45000,
    homeLoanInterestRatePct: 5.75,
    monthlyRepayment: 1600,
    remainingLoanTermYears: 3,
    livingCosts: 3900,
    food: 250,
    utilities: 4400,
    insurance: 3100,
    ratesPropertyCosts: 5200,
    otherExpenses: 11800,
    subscriptions: 95,
    phoneInternet: 145,
    privateHealth: 310,
    transport: 85,
    vehicleCosts: 2500,
    annualInvestingTarget: 10000,
    extraSuperContributions: 6000,
    emergencyFundTarget: 70000,
    investmentTarget: 420000,
    superTarget: 1700000,
    debtTarget: 0,
    netWorthTarget: 3000000,
    extraIncomeItems: [
      { id: "income-pension-ready", name: "Part-time consulting", amount: 18000, category: "other", owner: "person1", passiveIncome: false },
      { id: "income-interest-ready", name: "Interest income", amount: 9000, category: "interest", owner: "joint", passiveIncome: true },
    ],
  }),
];

window.FFS_DATA = {
  disclaimer: "This tool is for education and modelling only and is not financial advice. Tax, STSL compulsory repayments and cashflow figures are estimates for modelling.",
  samplePlans,
  demoPlan: samplePlans[1].plan,
  demoScenarioAdjustments: [
    {
      name: "Current sample plan",
      notes: "Fictional starting position from the selected sample plan.",
      adjustments: {},
    },
    {
      name: "Invest extra $10k",
      notes: "Adds $10,000 per year to the investment target.",
      adjustments: { annualInvestingTarget: 10000 },
    },
    {
      name: "Lower expenses",
      notes: "Reduces yearly expenses by a dummy $7,500.",
      adjustments: { otherExpenseAnnualChange: -7500 },
    },
  ],
};
