import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import {load} from '../scripts/fi-cashflow-fixture.mjs';
const {CALC,UI,ENGINE}=load();
const plain=x=>JSON.parse(JSON.stringify(x));
export function splitPlan(treatment='cash',yieldPct=3){
 const p=CALC.emptyPlan();Object.assign(p.personal,{person1Age:43,person2Age:0,fullRetirementAge:65,targetAnnualSpending:40000});
 Object.assign(p.investing,{expectedInvestmentReturnPct:7,expectedSuperReturnPct:6.5,inflationPct:0,annualInvestingTarget:0});
 p.assetItems=[{id:'portfolio',category:'shares',name:'Portfolio A',owner:'person1',value:500000,investmentReturnMode:'totalReturn',expectedTotalReturnPct:7,expectedIncomeYieldPct:yieldPct,incomeTreatment:treatment}];
 p.incomeItems=[{id:'salary',type:'salaryWages',owner:'person1',amount:100000,frequency:'annually'}];
 p.expenseItems=[{id:'living',category:'living',amount:40000,frequency:'annually'}];return p;
}
test('500k at 7/3 reconciles 35k total, 15k cash and 20k retained',()=>{const a=CALC.investmentReturnAmounts(splitPlan().assetItems[0]);assert.equal(a.totalReturn,35000);assert.equal(a.cashIncome,15000);assert.equal(a.retainedReturn,20000);assert.equal(a.retainedReturn+a.cashIncome,a.totalReturn);});
test('reinvest retains 35k, supplies no cash, but 15k remains taxable',()=>{const p=splitPlan('reinvest');const a=CALC.investmentReturnAmounts(p.assetItems[0]);assert.equal(a.retainedReturn,35000);assert.equal(a.cashIncome,0);assert.equal(a.taxableIncome,15000);const b=CALC.incomeBreakdown(p);assert.equal(b.total,100000);assert.equal(b.taxableTotal,115000);assert.equal(CALC.passiveIncomeBreakdown(p).total,0);});
test('cash and reinvest income have the same taxable amount and tax',()=>{const a=CALC.calculatePlan(splitPlan()),b=CALC.calculatePlan(splitPlan('reinvest'));assert.deepEqual(a.taxEstimate,b.taxEstimate);assert.equal(a.annualGrossIncome-b.annualGrossIncome,15000);assert.equal(a.finalProjectedCashSurplus-b.finalProjectedCashSurplus,15000);});
test('linked dividend amount is informational and generated once',()=>{const p=splitPlan();p.incomeItems.push({id:'div',type:'dividends',linkedAssetId:'portfolio',owner:'person2',amount:99999,frequency:'annually'});const a=CALC.calculatePlan(p);assert.equal(a.annualPassiveIncome,15000);assert.equal(a.annualGrossIncome,115000);assert.equal(CALC.incomeBreakdown(p).person1Taxable,115000);assert.equal(CALC.incomeBreakdown(p).person2Taxable,0);});
test('multiple linked references do not multiply generated income',()=>{const p=splitPlan();p.incomeItems.push(...['a','b'].map(id=>({id,type:'distributions',linkedAssetId:'portfolio',amount:10000,frequency:'annually'})));assert.equal(CALC.incomeBreakdown(p).total,115000);});
test('unlinked dividends and unrelated trust income are retained',()=>{const p=splitPlan();p.incomeItems.push({id:'div',type:'dividends',amount:2000},{id:'trust',type:'distributions',amount:3000,confirmedSeparateInvestmentIncome:true});assert.equal(CALC.passiveIncomeBreakdown(p).total,20000);assert.equal(CALC.investmentIncomeReviewItems(p).length,1);});
for(const yieldPct of [0,7])test(`yield boundary ${yieldPct} is valid`,()=>{const a=CALC.investmentReturnAmounts(splitPlan('cash',yieldPct).assetItems[0]);assert.equal(a.retainedReturn+a.cashIncome,35000);assert.equal(a.retainedReturn,yieldPct===0?35000:0);});
test('yield greater than return and invalid modes fail without clamping',()=>{assert.throws(()=>CALC.calculatePlan(splitPlan('cash',8)),/Income yield cannot exceed/);assert.throws(()=>CALC.investmentReturnAmounts({...splitPlan().assetItems[0],incomeTreatment:'unknown'}),/Choose whether/);assert.throws(()=>CALC.investmentReturnAmounts({...splitPlan().assetItems[0],expectedIncomeYieldPct:-1}),/non-negative/);});
test('mixed portfolios use independent rates and treatments',()=>{const p=splitPlan();p.assetItems[0].value=300000;p.assetItems.push({...p.assetItems[0],id:'b',name:'B',value:200000,expectedTotalReturnPct:8,incomeTreatment:'reinvest'});const r=CALC.calculatePlan(p);assert.equal(r.projectedFinancialInvestmentGrowth,28000);assert.equal(r.annualPassiveIncome,9000);assert.equal(r.combinedWealthCreation,37000);assert.equal(r.investmentReturnSummary.totalReturn,37000);});
test('monthly contributions keep existing beginning-of-month timing',()=>{const p=splitPlan('reinvest',0);const components=CALC.investmentPortfolioComponents(p,500000);const a=CALC.projectSplitInvestmentYear(components,52000);const legacy=splitPlan();delete legacy.assetItems[0].investmentReturnMode;legacy.investing.annualInvestingTarget=52000;legacy.incomeItems[0].amount=300000;const b=CALC.calculatePlan(legacy).investmentProjection[0];assert.ok(Math.abs(a.holdings.reduce((n,a)=>n+a.value,0)-b.closingBalance)<.2);});
test('every accumulation year reconciles returns and reuses tax/affordability',()=>{const p=splitPlan();p.investing.annualInvestingTarget=52000;const r=CALC.calculatePlan(p);for(const row of r.investmentProjection){assert.ok(Math.abs(row.investmentGrowth+row.investmentCashIncome-row.totalInvestmentReturn)<.02);assert.ok(Math.abs(row.openingBalance+row.annualContribution+row.investmentGrowth-row.closingBalance)<.02);assert.equal(row.annualContribution,r.accumulationCashflowProjection[row.year-1].investmentContribution);}assert.ok(r.investmentProjection[1].investmentCashIncome>r.investmentProjection[0].investmentCashIncome);});
test('negative surplus never invents planned contributions',()=>{const p=splitPlan();p.expenseItems[0].amount=200000;p.investing.annualInvestingTarget=52000;const r=CALC.calculatePlan(p);assert.ok(r.finalProjectedCashSurplus<0);assert.equal(r.investmentProjection[0].annualContribution,0);});
test('review warning conditions and persistent separate confirmation',()=>{const p=splitPlan();const d={id:'d',type:'dividends',amount:20000};p.incomeItems.push(d);assert.equal(CALC.investmentIncomeReviewItems(p).length,1);d.confirmedSeparateInvestmentIncome=true;assert.equal(CALC.investmentIncomeReviewItems(p).length,0);delete d.confirmedSeparateInvestmentIncome;d.linkedAssetId='portfolio';assert.equal(CALC.investmentIncomeReviewItems(p).length,0);delete d.linkedAssetId;p.assetItems=[];assert.equal(CALC.investmentIncomeReviewItems(p).length,0);});
test('configured return flows through FI balances without changing target',()=>{const a=CALC.calculatePlan(splitPlan()),b=CALC.calculatePlan(splitPlan('reinvest'));assert.equal(a.targetCapital,b.targetCapital);assert.equal(a.accessibleFiAssets,b.accessibleFiAssets);assert.ok(a.investmentProjection[5].closingBalance<b.investmentProjection[5].closingBalance);assert.ok(a.financialFreedomProgressProjection[5].progress<b.financialFreedomProgressProjection[5].progress);});
test('retirement snapshot preserves independent components and source IDs',()=>{const p=splitPlan();p.incomeItems.push({id:'div',type:'dividends',amount:1000,linkedAssetId:'portfolio'});const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const saved=plain(draft);p.assetItems[0].expectedTotalReturnPct=40;p.assetItems[0].incomeTreatment='reinvest';assert.equal(saved.accessibleInvestments.components[0].expectedTotalReturnPct,7);assert.deepEqual(saved.accessibleInvestments.components[0].sourceIncomeIds,['div']);const r=UI.runSemiRetirementProjection(ENGINE,saved);assert.equal(r.result.validation.isValid,true);});
test('retirement cash income is paid once, taxes reinvested yield, and earnings reconcile',()=>{for(const mode of ['cash','reinvest']){const p=splitPlan(mode);p.personal.fullRetirementAge=43;const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const r=UI.runSemiRetirementProjection(ENGINE,draft);assert.equal(r.result.validation.isValid,true);const y=r.result.years[0];assert.equal(y.passiveIncome.filter(x=>x.linkedAssetId==='portfolio').length,1);const income=y.passiveIncome.find(x=>x.linkedAssetId==='portfolio');assert.equal(income.taxableIncome,15000);assert.equal(income.cashIncome,mode==='cash'?15000:0);assert.ok(y.household.splitInvestmentReturns.length);for(const x of y.household.splitInvestmentReturns)assert.ok(Math.abs(x.retainedReturn+x.cashIncome-x.totalReturn)<.02);}});
test('scenario return adjustment revalidates yield',()=>{const p=splitPlan();const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));draft.accessibleInvestments.annualReturnRatePct=2;const r=UI.runSemiRetirementProjection(ENGINE,draft);assert.equal(r.result.validation.isValid,false);});

for(const fixture of JSON.parse(readFileSync(new URL('./fixtures/investment-return-legacy.json',import.meta.url),'utf8'))) {
 test(`legacy ${fixture.name}: all results and saved scenario match pre-change main`,()=>{
  const c={console,Date:class extends Date{constructor(...args){super(...(args.length?args:['2026-09-29T00:00:00Z']));}static now(){return Date.parse('2026-09-29T00:00:00Z');}}};c.globalThis=c;
  for(const file of ['calculator.js','semiRetirementProjection.js','semiRetirementUi.js'])vm.runInNewContext(readFileSync(new URL('../'+file,import.meta.url),'utf8'),c);
  const calc=c.FFSCalculator.calculatePlan(fixture.plan),{draft}=c.FFSSemiRetirementUi.buildSemiRetirementScenarioDefaults(fixture.plan,calc);
  const record={calc,draft,retirement:c.FFSSemiRetirementUi.runSemiRetirementProjection(c.FFSSemiRetirementProjection,draft)};
  assert.equal(createHash('sha256').update(JSON.stringify(record)).digest('hex'),fixture.sha256);
 });
}
test('saved scenario round trip remains identical after current plan changes',()=>{const p=splitPlan();const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const snapshot=JSON.stringify(draft);const first=plain(UI.runSemiRetirementProjection(ENGINE,JSON.parse(snapshot)));p.assetItems[0].value=1;p.assetItems[0].expectedTotalReturnPct=1;p.assetItems[0].expectedIncomeYieldPct=0;CALC.calculatePlan(p);assert.deepEqual(plain(UI.runSemiRetirementProjection(ENGINE,JSON.parse(snapshot))),first);});
test('retirement exhausted holdings stop generating investment income',()=>{const p=splitPlan();p.personal.fullRetirementAge=43;p.expenseItems[0].amount=300000;const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const r=UI.runSemiRetirementProjection(ENGINE,draft).result;assert.equal(r.validation.isValid,true);const zero=r.years.findIndex(y=>y.household.closingAccessibleInvestmentBalance===0);assert.ok(zero>=0);for(const y of r.years.slice(zero+1))assert.equal(y.passiveIncome.find(i=>i.linkedAssetId==='portfolio').cashIncome,0);assert.ok(r.summary.firstUnfundedSpending);});
test('super growth and property projection are unchanged by investment treatment',()=>{const a=splitPlan(),b=splitPlan('reinvest');a.assets.superPerson1=b.assets.superPerson1=100000;const x=CALC.calculatePlan(a),y=CALC.calculatePlan(b);assert.deepEqual(x.superProjection,y.superProjection);assert.equal(x.projectedPropertyGrowth,y.projectedPropertyGrowth);});
test('legacy input without structured assets still receives a targeted warning',()=>{const p=splitPlan();p.assets.sharesEtfs=500000;p.assetItems=[];p.incomeItems.push({id:'d',type:'dividends',amount:20000});assert.equal(CALC.investmentIncomeReviewItems(p).length,1);assert.equal(CALC.incomeBreakdown(p).total,120000);});
test('cash retirement applies only the residual rate to midpoint holdings',()=>{const p=splitPlan();p.personal.fullRetirementAge=43;const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const y=UI.runSemiRetirementProjection(ENGINE,draft).result.years[0];assert.ok(Math.abs(y.household.accessibleInvestmentEarnings-y.household.accessibleEarningsBasis*.04)<.02);assert.equal(y.passiveIncome.find(i=>i.linkedAssetId==='portfolio').cashIncome,15000);});
test('100 percent income portion retains no growth in retirement',()=>{const p=splitPlan('cash',7);p.personal.fullRetirementAge=43;p.expenseItems[0].amount=1000000;const {draft}=UI.buildSemiRetirementScenarioDefaults(p,CALC.calculatePlan(p));const rows=UI.runSemiRetirementProjection(ENGINE,draft).result.years;assert.equal(rows[0].household.accessibleInvestmentEarnings,0);assert.equal(rows[1].passiveIncome.find(i=>i.linkedAssetId==='portfolio').cashIncome,0);});
test('explicit opt-in yield suggestion preserves linked taxable amount',()=>{const p=splitPlan();delete p.assetItems[0].investmentReturnMode;p.incomeItems.push({id:'d',linkedAssetId:'portfolio',type:'dividends',amount:20000});assert.equal(CALC.linkedInvestmentIncomeYield(p,p.assetItems[0]),4);assert.equal(CALC.incomeBreakdown(p).taxableTotal,120000);});
test('schema migration preserves settings and stable income relationship',()=>{const c={console};c.globalThis=c;vm.runInNewContext(readFileSync(new URL('../plan-schema.js',import.meta.url),'utf8'),c);const p=splitPlan();p.incomeItems.push({id:'d',type:'dividends',linkedAssetId:'portfolio',amount:20000,confirmedSeparateInvestmentIncome:false});const result=c.FFSPlanSchema.migrate(p);const migrated=result.plan || result;assert.equal(migrated.assetItems.find(a=>a.id==='portfolio').expectedIncomeYieldPct,3);assert.equal(migrated.incomeItems.find(i=>i.id==='d').linkedAssetId,'portfolio');assert.equal(migrated.incomeItems.find(i=>i.id==='d').confirmedSeparateInvestmentIncome,false);});
test('guided setup saves authoritative yield and rejects invalid split',()=>{const c={console,FFSCalculator:CALC};c.globalThis=c;vm.runInNewContext(readFileSync(new URL('../linked-setup.js',import.meta.url),'utf8'),c);const p=splitPlan();const draft={name:'New portfolio',investmentType:'shares',value:500000,owner:'person1',hasLoan:false,investmentReturnMode:'totalReturn',expectedTotalReturnPct:7,expectedIncomeYieldPct:3,incomeTreatment:'cash'};const r=c.FFSLinkedSetup.upsertInvestment(p,draft,{makeId:prefix=>'new-'+prefix});assert.equal(r.ok,true);assert.equal(CALC.passiveIncomeBreakdown(r.plan).total,30000);assert.equal(c.FFSLinkedSetup.upsertInvestment(p,{...draft,expectedIncomeYieldPct:8}).ok,false);});
