export const DEFAULT_SUITE_TIMEOUT_MS = 120_000;

export const ACTIVE_TEST_SUITES = [
  { id: "future-you-default", file: "tests/future-you-default.test.mjs", groups: ["all", "mjs", "presentation"] },
  { id: "new-plan-projection-default", file: "tests/new-plan-projection-default.test.mjs", groups: ["all", "mjs", "presentation"] },
  { id: "educational-wording", file: "tests/educational-wording.test.mjs", groups: ["all", "mjs", "presentation"] },
  { id: "minor-presentation", file: "tests/minor-presentation.test.mjs", groups: ["all", "mjs", "presentation"] },
  { id: "investment-asset-ux", file: "tests/investment-asset-ux.test.mjs", groups: ["all", "mjs", "investment-return"] },
  { id: "investment-return-split", file: "tests/investment-return-split.test.mjs", groups: ["all", "mjs", "investment-return"] },
  { id: "financial-report-presentation", file: "tests/financial-report-presentation.test.mjs", groups: ["all", "mjs", "report"] },
  { id: "saved-retirement-cards", file: "tests/saved-retirement-cards.test.mjs", groups: ["all", "mjs", "semi-retirement", "saved-cards"] },
  { id: "final-modelling-assurance", file: "tests/final-modelling-assurance.test.mjs", groups: ["all", "mjs", "assurance"] },
  { id: "fi-wealth-cashflow", file: "tests/fi-wealth-cashflow.test.mjs", groups: ["all", "mjs", "fi-cashflow"] },
  { id: "retirement-exhaustion-retained-assets", file: "tests/retirement-exhaustion-retained-assets.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "calculations", file: "tests/calculations.test.ts", nodeArgs: ["--experimental-strip-types"], groups: ["all"] },
  { id: "engagement", file: "tests/engagement.test.ts", nodeArgs: ["--experimental-strip-types"], groups: ["all"] },
  { id: "tax-integration", file: "tests/financial-freedom-tax-integration.test.mjs", groups: ["all", "mjs"] },
  { id: "financial-progress-history", file: "tests/financial-progress-history.test.mjs", groups: ["all", "mjs"] },
  { id: "calculation-audit-2026-27", file: "tests/calculation-audit-2026-27.test.mjs", groups: ["all", "mjs", "audit"] },
  { id: "main-calculator-zero-balance-loan-r3-blocker", file: "tests/main-calculator-zero-balance-loan-r3-blocker.test.mjs", groups: ["all", "mjs", "audit", "r3-blocker"] },
  { id: "semi-retirement-projection", file: "tests/semi-retirement-projection.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "semi-retirement-ui", file: "tests/semi-retirement-ui.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "semi-retirement-integration-v1", file: "tests/semi-retirement-integration-v1.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "stage-a", file: "tests/semi-retirement-debt-property-stage-a.test.mjs", groups: ["all", "mjs", "semi-retirement"] },
  { id: "stage-a1", file: "tests/semi-retirement-debt-property-stage-a1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-a1"] },
  { id: "stage-b", file: "tests/semi-retirement-debt-property-stage-b.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b"] },
  { id: "stage-b1", file: "tests/semi-retirement-debt-property-stage-b1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b1"] },
  { id: "stage-b1a", file: "tests/semi-retirement-debt-property-stage-b1a.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-b1a"] },
  { id: "stage-c", file: "tests/semi-retirement-debt-property-stage-c.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-c"] },
  { id: "stage-c1", file: "tests/semi-retirement-debt-property-stage-c1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-c1"] },
  { id: "stage-d", file: "tests/semi-retirement-debt-property-stage-d.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-d"] },
  { id: "stage-e", file: "tests/semi-retirement-debt-property-stage-e.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-e"] },
  { id: "stage-e1", file: "tests/semi-retirement-debt-property-stage-e1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-e1"] },
  { id: "stage-g2ea", file: "tests/semi-retirement-surplus-routing-g2ea.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2ea"] },
  { id: "stage-g2es", file: "tests/semi-retirement-concessional-events-g2es.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2es"] },
  { id: "stage-g2es1", file: "tests/semi-retirement-concessional-tax-treatment-g2es1.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2es1"] },
  { id: "stage-g2g", file: "tests/semi-retirement-follow-up-g2g.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2g"] },
  { id: "stage-g2h", file: "tests/sample-plans-multi-comparison-g2h.test.mjs", groups: ["all", "mjs", "semi-retirement", "stage-g2h"] },
  { id: "ai-containment-r1", file: "tests/ai-containment-r1.test.mjs", groups: ["all", "mjs", "r1-ai"] },
  { id: "browser-security-r4a", file: "tests/browser-security-r4a.test.mjs", groups: ["all", "mjs", "r4a"] },
  { id: "data-durability-r5", file: "tests/data-durability-r5.test.mjs", groups: ["all", "mjs", "r5"] },
  { id: "integrated-release-candidate-r6", file: "tests/integrated-release-candidate-r6.test.mjs", groups: ["all", "mjs", "r6"] },
  { id: "stage-readiness-r6a", file: "tests/stage-readiness-r6a.test.mjs", groups: ["all", "mjs", "r6a"] },
  { id: "canonical-salary-timing-r6b", file: "tests/canonical-salary-timing-r6b.test.mjs", groups: ["all", "mjs", "r6b"] },
  { id: "retirement-timing-presentation-r6c", file: "tests/retirement-timing-presentation-r6c.test.mjs", groups: ["all", "mjs", "semi-retirement", "r6c"] },
  { id: "completed-week-edit-gating-r6d", file: "tests/completed-week-edit-gating-r6d.test.mjs", groups: ["all", "mjs", "r6d"] },
  { id: "dst-safe-week-bucketing-r6e", file: "tests/dst-safe-week-bucketing-r6e.test.mjs", groups: ["all", "mjs", "r6e"] },
  { id: "linked-investment-setup", file: "tests/linked-investment-setup.test.mjs", groups: ["all", "mjs", "linked-setup", "stage1"] },
  { id: "trust-readiness-stage1", file: "tests/trust-readiness-stage1.test.mjs", groups: ["all", "mjs", "stage1"] },
  { id: "consumer-first-stage2", file: "tests/consumer-first-stage2.test.mjs", groups: ["all", "mjs", "stage2"] },
  { id: "consumer-ux-stage2b", file: "tests/consumer-ux-stage2b.test.mjs", groups: ["all", "mjs", "stage2b"] },
  { id: "canonical-plan-stage3", file: "tests/canonical-plan-stage3.test.mjs", groups: ["all", "mjs", "stage3"] },
  { id: "canonical-integrity-stage3a", file: "tests/canonical-integrity-stage3a.test.mjs", groups: ["all", "mjs", "stage3", "stage3a"] },
  { id: "release-parity-stage4", file: "tests/release-parity-stage4.test.mjs", groups: ["all", "mjs", "stage4"] },
];

export const SYNTAX_CHECK_FILES = [
  "app.js",
  "security.js",
  "api/ai-insights.js",
  "calculator.js",
  "semiRetirementProjection.js",
  "semiRetirementUi.js",
  "weekly-plan.js",
  "weekly-planner-export.js",
  "linked-setup.js",
  "trust-readiness.js",
  "dialog-controller.js",
  "consumer-setup.js",
  "plan-schema.js",
  "legacy-plan-adapter.js",
  "plan-selectors.js",
  "plan-mutations.js",
  "scenario-overlay.js",
  "scripts/run-tests.mjs",
  "scripts/verify-test-inventory.mjs",
  "scripts/run-syntax-checks.mjs",
  "scripts/run-test-suite-worker.mjs",
  "scripts/runner-self-test.mjs",
  "scripts/scan-secrets.mjs",
  "scripts/scan-secrets-self-test.mjs",
  "scripts/test-inventory.mjs",
  "scripts/r1-numerical-parity.mjs",
  "scripts/r1-numerical-parity-self-test.mjs",
  "scripts/r6-sample-metrics.mjs",
  "scripts/verify-browser-security.mjs",
  "tests/main-calculator-zero-balance-loan-r3-blocker.test.mjs",
  "tests/browser-security-r4a.test.mjs",
  "tests/data-durability-r5.test.mjs",
  "tests/integrated-release-candidate-r6.test.mjs",
  "tests/stage-readiness-r6a.test.mjs",
  "tests/canonical-salary-timing-r6b.test.mjs",
  "tests/retirement-timing-presentation-r6c.test.mjs",
  "tests/completed-week-edit-gating-r6d.test.mjs",
  "tests/dst-safe-week-bucketing-r6e.test.mjs",
  "tests/linked-investment-setup.test.mjs",
  "tests/trust-readiness-stage1.test.mjs",
  "tests/stage1-browser-workflows.mjs",
  "tests/consumer-first-stage2.test.mjs",
  "tests/consumer-ux-stage2b.test.mjs",
  "tests/canonical-plan-stage3.test.mjs",
  "tests/canonical-integrity-stage3a.test.mjs",
  "tests/release-parity-stage4.test.mjs",
  "tests/helpers/weekly-dst-probe.mjs",
];
